- id: 9
  name: "Gen Mobile Plan"
  category: "Plan"
  price: 10.00
  description: "High speed data:

Enjoy 1GB of data at 5G/4G speed and at 128 kbps thereafter.

Unlimited calling to 100+ international destinations:

Keep in touch with friends and family around the world while in the U.S. with unlimited calling to 100+ international destinations. You can call up to 20 unique international phone numbers during the month. See genmobile.com/intl for list of unlimited destinations.

Mobile hotspot:

Use your smartphone as a Wi-Fi hotspot for other devices like tablets, laptops and more. Data pulls from your plan’s 5G/4G speed data allotment.."
  image: "https://placehold.co/400x300/1E40AF/FFFFFF?text=Basic+Plan"

- id: 10
  name: "Freedom Plus Plan"
  category: "Plan"
  price: 49.99
  description: "Get 50GB of premium high-speed data, unlimited talk & text, and mobile hotspot capabilities. Billed monthly."
  image: "https://placehold.co/400x300/DC2626/FFFFFF?text=Plus+Plan"

- id: 11
  name: "Unlimited Premium"
  category: "Plan"
  price: 79.99
  description: "Truly unlimited premium data that never slows down. Includes international calling and streaming perks. Billed monthly."
  image: "https://placehold.co/400x300/3B82F6/FFFFFF?text=Unlimited"

- id: 1
  name: "Exclusive Verizon savings"
  category: "Internet Service"
  price: 84.99/mo

  description: "
1 Gig includes:
Availability varies. Gigabit network connection to your home. Wired and wireless speeds vary due to device limits, multiple users, network & other factors. See verizon.com/yourspeed for more info.
Additional Extenders are available to rent or purchase. Verizon owns the equipment provided with your plan, including the Verizon Router and Wi-Fi extender. If you choose to disconnect service, you must return equipment within 30 days, or you'll incur charges 

    Must be 18 years of age or older to enroll.

    U.S. only.

    Access content from each service separately.

    Disney+ may be upgraded and downgraded via Disney+.

    Hulu may be upgraded and downgraded via Hulu.

    ESPN+ may be upgraded and downgraded via ESPN+.

    Location data is required to watch certain content.

    Enrolling in the Disney+, Hulu, ESPN+ (With Ads) plan perk may affect existing subscriptions to a Disney bundle, Disney+, Hulu, or ESPN+. Review the Terms & Conditions for instructions.

    EXISTING DISNEY+, HULU OR ESPN+ SUBSCRIBERS: Offer will not automatically replace existing subscription(s). After enrolling in the Disney+, Hulu, ESPN+ (With Ads) plan perk, you will need to complete account setup separately for each service. Managing subscriptions may be required to avoid multiple subscriptions and corresponding charges.

    For existing Hulu subscribers, you may need to manage your subscription to complete account setup.

    $6.99/mo perk savings based on the current $16.99/mo that Verizon subscribers pay for Disney+, Hulu, ESPN+ (With Ads) less the $10/mo myHome perk.

    Fios Home Internet plans (except Classic Standalone) are eligible to purchase the Disney+, Hulu, ESPN+ (With Ads) perk.

    Subject to Disney+, Hulu, and ESPN+ Subscriber Agreement. . ."
  image: "https://placehold.co/400x300/1E40AF/FFFFFF?text=Laptop+X1"

- id: 2
  name: "Samsung Galaxy Tab A9 (Sm-x115) 8.7inch 64GB Cellular ,New ,Sealed"
  category: "Tablet"
  price: 249.99
  description: "New Sealed

4GB of Ram
Cellular
Unlocked
8.7 inches
Android 13 with One UI 5.1
Rear camera is 8MP
Front Camera is 2MP
5100 mAh Battery."
  image: "https://placehold.co/400x300/DC2626/FFFFFF?text=Tablet+10"

- id: 3
  name: "Samsung Galaxy S25 128GB 5G

Unlocked by Samsung, Dual Sim

New Sealed "
  category: "Phone"
  price: 799.00
  description: "The following features are available for the Samsung Galaxy S25
: 

    Design: A durable build with an Armor Aluminum frame and Corning Gorilla Glass Victus 2 on both the front and back.
    Display: A 6.2-inch Dynamic LTPO AMOLED 2X display with a variable 120Hz refresh rate and a peak brightness of 2,600 nits.
    Performance: Equipped with the Qualcomm Snapdragon 8 Elite for Galaxy processor and 12GB of RAM.
    Camera: A triple rear camera system featuring a 50MP main lens, a 12MP ultrawide lens, and a 10MP telephoto lens with 3x optical zoom. The front camera is 12MP.
    AI capabilities: Features a suite of Galaxy AI tools, including text summarization, a writing assistant, and image editing features.
    Software: Runs on Android 15 with One UI 7 out of the box and is promised 7 years of OS updates.
    Battery: A 4,000 mAh battery that supports 25W wired fast charging and 15W wireless charging.
    Durability: Offers an IP68 rating for water and dust resistance.
    Audio: Features stereo speakers."
  image: "s25_plus_navy__87552.jpg"

- id: 4
  name: "2TB NVMe SSD - Red Line"
  category: "Wifi"
  price: 189.50
  description: "Blazing fast 2TB NVMe SSD for gaming and high-performance computing. 7000MB/s read speed."
  image: "https://placehold.co/400x300/8B5CF6/FFFFFF?text=2TB+SSD"

- id: 5
  name: "Wireless Mechanical Keyboard"
  category: "Wifi"
  price: 119.99
  description: "Tactile brown switches with customizable red backlighting. US layout."
  image: "https://placehold.co/400x300/F97316/FFFFFF?text=Keyboard"

- id: 6
  name: "NewRock Desktop Elite"
  category: "Internet Service"
  price: 1999.00
  description: "High-end gaming desktop with RTX 4080 and i9 processor. Ready for 4K gaming."
  image: "https://placehold.co/400x300/064E3B/FFFFFF?text=Desktop+Elite"

- id: 7
  name: "Tecno Spark Go 1S , 64GB , Dual Sim , 6.67-inch , Unlocked , New , Sealed"
  category: "Phone"
  price: 249.99
  description: "Processor: MediaTek Helio G50 octa-core chipset
    RAM and storage: 3GB RAM and 64GB of internal storage. The storage is expandable via a microSDXC card.
    Display: A 6.67-inch IPS LCD with a 90Hz refresh rate and a resolution of 720 x 1600 pixels.
    Cameras: 13MP main rear camera with phase detection autofocus (PDAF) and a dual LED flash. The front-facing camera is 8MP and also has a flash.
    Battery: A 5,000mAh battery that supports 15W fast charging via a USB Type-C port.
    Operating system: Android 14 (Go edition) with Tecno's HiOS 14.
    Other features: Dual SIM support, IPX4 water resistance, rear-mounted fingerprint sensor, and facial recognition for security. "
  image: "images/tecno_spark_go_1s_black__76702.jpg"

- id: 8
  name: "Tablet Stylus Pro"
  category: "Wifi"
  price: 49.99
  description: "High-precision stylus for NewRock and Nova tablets. Magnetic attachment."
  image: "https://placehold.co/400x300/1D4ED8/FFFFFF?text=Stylus"

