- id: 9
  name: " Friggs Mobile Plan"
  category: "Plan"
  price: 30.00
  description: "High speed data:
 A new generation of wireless carrier
$30.00/mo
3 GB of 5G/4G high speed data
Unlimited nationwide talk & text
Bitcoin rewards every month
Plan Details >

3 GB
InternetDrop
3GB of 5G/4G high speed data Data speed reduces after 3GB 3GB Mobile HotSpot included
Calling & TextingDrop
Unlimited nationwide talk & text WiFi calling included
eSIMDrop
Bring your own device, unlocked and compatible
ConditionsDrop
No contract duration
CashbackDrop
Get 5% Bitcoin cashback on your monthly service fee. Get 10% cashback by adding plans for family or friends. Rewards are deposited into your fliggs wallet, you can choose to receive them in Bitcoin, Digital USD or another currencies. Wallet access made simple and secure.
Broadband factsDrop
The smarter choice.
Stop overpaying, start saving.

Choose an affordable mobile plan with low, guaranteed prices. Change or cancel your plan anytime, every month. You are in full control.
Enjoy the fastest 5G network.

Enjoy premium wireless on the fastest and largest 5G network in the US. All plans include 5G Ultra at no extra cost, which means you will get even faster 5G speeds.
Get monthly Bitcoin cashback.

Get back 5% to 10% of your service fee every month. The cashback is deposited in your fliggs wallet in Bitcoin or digital USD.
Mobile plans that pay you back

Earn a share of your service fee in Bitcoin, every month.
Bitcoin
Bitcoin
Surf the fastest 5G network
0
0
0
Easy to use.
1

Install the fliggs mobile app from Google Play Store or Apple App Store.
2

Bring your own phone, compatible and unlocked.
3

Pick your plan, transfer your number or request a new one.
Stay connected anytime, everywhere.
bgImage
Play

Enjoy serious data privacy.

1
We do not exploit your information. We do not sell your data.

2
We apply the most robust data standards, across the entire nation.

3
We guard your personal data, and our commitment to privacy remains absolute.

You'll love fliggs
Our partnerships
5g network
r17
aws icon
logo

Want to stay up to date? Sign up for the fliggs newsletter.
Email Address

Get the fliggs app.
appStoreIcon
appStoreIcon

Features

    5G Coverage

    Bring your own phone

    Bitcoin rewards

    Wallet

    Roaming packages

    Data boosters

    eSIM

    WiFi calling

    Mobile Hotspot

Support

    FAQ

    Web3 Glossary

About fliggs

    News

    Why fliggs

    Contact us

    TWITTER icon
    LINKEDIN icon
    INSTAGRAM icon
    FACEBOOK icon

    © 2025 fliggsmobile.com
    Privacy Policy
    Terms & Conditions
    Wallet Terms & Conditions
    Accessibility
    Acceptable Use Policy
    911 and E911 disclosure
    Do not sell or share my Information

.."
  image: "https://placehold.co/400x300/1E40AF/FFFFFF?text=Basic+Plan"

- id: 10
  name: "  Consumer Cellular Plan"
  category: "Plan"
  price: 45.00
  description: " 
Unlimited Talk/Txt/20GB Data
1 Line
Included
Unlimited Data
Unlimited Talk & Text
$45/Month
$45 due monthly
. ."
  image: "https://placehold.co/400x300/DC2626/FFFFFF?text=Plus+Plan"

- id: 11
  name: "  AT&T Unlimited Plan Apple iPhone 17 Pro Max - 1TB    "
  category: "Plan"
  price: 133.93
  description: "Due monthly*
$133.93
Due today
$142.00
*Plus taxes and fees.See disclosures

Your services will auto-renew monthly at then-current rates (less any discounts or promotions) unless you cancel by visiting att.com/cancel-info.
Price details
Due monthly
$133.93
Apple iPhone 17 Pro Max - 1TB
$44.45
Price for 36 mos. at 0% APR
ONLINE ONLY: You will get an additional $200 in monthly bill credits ($5.56/mo. for 36 months) with new voice on elig. unlimited plan (speed restr's apply). Credits start within 3 bills.
 
AT&T Unlimited Premium® PL plan
See discounts
$85.99
AT&T Administrative/Regulatory Cost Recovery Fee
$3.49
Government taxes and additional AT&T fees extra.
See details
Due only on first bill
$0.00
Activation fee
$0.00
Due today
$142.00
Next-day shipping fee
FREE
Apple iPhone 17 Pro Max - Deep Blue - 1TB
Estimated device sales tax
$142.00
Savings & promotions
AutoPay and paperless billing discount
. Billed monthly."
  image: "https://placehold.co/400x300/3B82F6/FFFFFF?text=Unlimited"

- id: 1
  name: "Verizon Home Internet 1GIG    "
  category: "Internet Service"
  price: 84.99

  description: "
$84.99/Mo*  1Gig includes:  
Availability varies. Gigabit network connection to your home. Wired and wireless speeds vary due to device limits, multiple users, network & other factors. See verizon.com/yourspeed for more info.
Additional Extenders are available to rent or purchase. Verizon owns the equipment provided with your plan, including the Verizon Router and Wi-Fi extender. If you choose to disconnect service, you must return equipment within 30 days, or you'll incur charges 

    Must be 18 years of age or older to enroll.

    U.S. only.

    Access content from each service separately.

    Disney+ may be upgraded and downgraded via Disney+.

    Hulu may be upgraded and downgraded via Hulu.

    ESPN+ may be upgraded and downgraded via ESPN+.

    Location data is required to watch certain content.

    Enrolling in the Disney+, Hulu, ESPN+ (With Ads) plan perk may affect existing subscriptions to a Disney bundle, Disney+, Hulu, or ESPN+. Review the Terms & Conditions for instructions.

    EXISTING DISNEY+, HULU OR ESPN+ SUBSCRIBERS: Offer will not automatically replace existing subscription(s). After enrolling in the Disney+, Hulu, ESPN+ (With Ads) plan perk, you will need to complete account setup separately for each service. Managing subscriptions may be required to avoid multiple subscriptions and corresponding charges.

    For existing Hulu subscribers, you may need to manage your subscription to complete account setup.

    $6.99/mo perk savings based on the current $16.99/mo that Verizon subscribers pay for Disney+, Hulu, ESPN+ (With Ads) less the $10/mo myHome perk.

    Fios Home Internet plans (except Classic Standalone) are eligible to purchase the Disney+, Hulu, ESPN+ (With Ads) perk.

    Subject to Disney+, Hulu, and ESPN+ Subscriber Agreement. . ."
  image: "https://placehold.co/400x300/1E40AF/FFFFFF?text=Laptop+X1"

- id: 2
  name: "Samsung Galaxy Tab A9 (Sm-x115) 8.7inch 64GB Cellular ,New ,Sealed"
  category: "Tablet"
  price: 249.99
  description: "New Sealed

4GB of Ram
Cellular
Unlocked
8.7 inches
Android 13 with One UI 5.1
Rear camera is 8MP
Front Camera is 2MP
5100 mAh Battery."
  image: "https://placehold.co/400x300/DC2626/FFFFFF?text=Tablet+10"

- id: 3
  name: "Samsung Galaxy S25 128GB 5G

Unlocked by Samsung, Dual Sim

New Sealed "
  category: "Phone"
  price: 799.99
  description: "The following features are available for the Samsung Galaxy S25
: 

    Design: A durable build with an Armor Aluminum frame and Corning Gorilla Glass Victus 2 on both the front and back.
    Display: A 6.2-inch Dynamic LTPO AMOLED 2X display with a variable 120Hz refresh rate and a peak brightness of 2,600 nits.
    Performance: Equipped with the Qualcomm Snapdragon 8 Elite for Galaxy processor and 12GB of RAM.
    Camera: A triple rear camera system featuring a 50MP main lens, a 12MP ultrawide lens, and a 10MP telephoto lens with 3x optical zoom. The front camera is 12MP.
    AI capabilities: Features a suite of Galaxy AI tools, including text summarization, a writing assistant, and image editing features.
    Software: Runs on Android 15 with One UI 7 out of the box and is promised 7 years of OS updates.
    Battery: A 4,000 mAh battery that supports 25W wired fast charging and 15W wireless charging.
    Durability: Offers an IP68 rating for water and dust resistance.
    Audio: Features stereo speakers."
  image: "s25_plus_navy__87552.jpg"

- id: 4
  name: "XNET WIFI Xplorer Hotspot 25GB
X Data Plan  "
  category: "Wifi"
  price: 65.00
  description: "
Xplorer Hotspot + Data Plan Bundle

    

hotspot
Xplorer Hotspot

The Xplorer Hotspot is your pocket-sized powerhouse for fast, reliable internet anywhere. With LTE Cat 6 speeds, dual-band Wi-Fi, and support for up to 16 devices, it’s perfect for travel, work, or staying connected off the grid.



 

Want to receive your device pre-activated? Click here to purchase a Device + Data Plan bundle
$199.00 Original price was: $199.00.$149.00Current price is: $149.00.
25 GB
X Data Plan
Data Plan *
	
Clear

25 GB of High-Speed Data
$65.00 / month
Activation
Activation Fee

To activate your vSIM and facilitate this service, a one-time Activation Fee is required. This fee is necessary to cover the costs involved in initiating the activation process with the carriers, generating usage reports, and maintaining the necessary infrastructure for continued connectivity.
$30.00

$229.00 $179.00 one time, and
$65.00 / month."
  image: "https://placehold.co/400x300/8B5CF6/FFFFFF?text=2TB+SSD"

- id: 5
  name: "XNET WIFI Xplorer Hotspot 50 GB X Data Plan "
  category: "Wifi"
  price: 75.00
  description: " Xplorer Hotspot

The Xplorer Hotspot is your pocket-sized powerhouse for fast, reliable internet anywhere. With LTE Cat 6 speeds, dual-band Wi-Fi, and support for up to 16 devices, it’s perfect for travel, work, or staying connected off the grid.


 

Want to receive your device pre-activated? Click here to purchase a Device + Data Plan bundle
$199.00 Original price was: $199.00.$149.00 Current price is: $149.00.
50 GB
X Data Plan
Data Plan *
	
Clear

50 GB of High-Speed Data
$75.00 / month
Activation
Activation Fee

To activate your vSIM and facilitate this service, a one-time Activation Fee is required. This fee is necessary to cover the costs involved in initiating the activation process with the carriers, generating usage reports, and maintaining the necessary infrastructure for continued connectivity.
$30.00

$229.00 $179.00 one time, and
$75.00 / month."
  image: "https://placehold.co/400x300/F97316/FFFFFF?text=Keyboard"

- id: 6
  name: "Verizon Home Internet 300 Mbps  "
  category: "Internet Service"
  price: 34.99
  description: " Up to 300 Mbps speeds
Download and upload speeds of up to 300 Mbps
Availability varies. Wired speeds advertised. Wireless speeds may vary due to device limits, multiple users, network & other factors. See Verizon.com/yourspeed for more info.
Router included at no additional cost
State-of-the art router featuring the latest Wi-Fi generation, Wi-Fi 6E, that provides more spectrum for increased speeds, better coverage, lower latency, built-in security, parental controls and more.
Verizon owns the router included with your plan. If you choose to disconnect service, you must return equipment within 30 days, or you'll incur charges.
3-year price lock guarantee**
So you don’t need to worry about unexpected price hikes.
**For new and existing myHome customers. Applies only to the then-current base monthly rate exclusive of any other setup and additional equipment charges, discounts or promotions, plan perk and any other third-party services.
."
  image: "https://placehold.co/400x300/064E3B/FFFFFF?text=Desktop+Elite"

- id: 7
  name: "Tecno Spark Go 1S , 64GB , Dual Sim , 6.67-inch , Unlocked , New , Sealed"
  category: "Phone"
  price: 249.99
  description: "Processor: MediaTek Helio G50 octa-core chipset
    RAM and storage: 3GB RAM and 64GB of internal storage. The storage is expandable via a microSDXC card.
    Display: A 6.67-inch IPS LCD with a 90Hz refresh rate and a resolution of 720 x 1600 pixels.
    Cameras: 13MP main rear camera with phase detection autofocus (PDAF) and a dual LED flash. The front-facing camera is 8MP and also has a flash.
    Battery: A 5,000mAh battery that supports 15W fast charging via a USB Type-C port.
    Operating system: Android 14 (Go edition) with Tecno's HiOS 14.
    Other features: Dual SIM support, IPX4 water resistance, rear-mounted fingerprint sensor, and facial recognition for security. "
  image: "images/tecno_spark_go_1s_black__76702.jpg"

- id: 8
  name: " Xnet Wifi Plan"
  category: "Wifi"
  price: 52.00
  description: "  
Data Plans

Get reliable high-speed data wherever you need it — at home, on the road, or off the grid.
4G Data Plans
25 GB
Great for travel or backup internet

As Low As:

$65

$52/mo

Pricing shown is based on advance annual payment. “As low as” price reflects a 20% discount for prepayment of 12 months. Standard monthly price is $65 when billed month-to-month.

25 GB of high-speed LTE data
Cancel anytime - no contracts
Pay monthly, or save with upfront payments
Save 5% when you pay for 3 months in advance
Save 10% when you pay for 6 months in advance
Save 20% when you pay for 12 months in advance        FFF?text=Stylus"

